/*

 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

package main

import (
	"fmt"
)

func main() {

	limit := 4000000
	ans := solve(limit)
	fmt.Println(ans)

}

func solve(limit int) int {

	cnt := 1
	ans := 2
	for a, b := 1, 2; b <= limit; a, b = b, a+b {
		if cnt%4 == 0 {
			ans += b
			cnt = 1
		}
		cnt += 1
	}
	return ans
}
